// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElAside: typeof import('element-ui/lib/aside')['default']
    ElAvatar: typeof import('element-ui/lib/avatar')['default']
    ElButton: typeof import('element-ui/lib/button')['default']
    ElCascader: typeof import('element-ui/lib/cascader')['default']
    ElContainer: typeof import('element-ui/lib/container')['default']
    ElDatePicker: typeof import('element-ui/lib/date-picker')['default']
    ElDivider: typeof import('element-ui/lib/divider')['default']
    ElDropdown: typeof import('element-ui/lib/dropdown')['default']
    ElDropdownItem: typeof import('element-ui/lib/dropdown-item')['default']
    ElDropdownMenu: typeof import('element-ui/lib/dropdown-menu')['default']
    ElFooter: typeof import('element-ui/lib/footer')['default']
    ElForm: typeof import('element-ui/lib/form')['default']
    ElFormItem: typeof import('element-ui/lib/form-item')['default']
    ElHeader: typeof import('element-ui/lib/header')['default']
    ElImage: typeof import('element-ui/lib/image')['default']
    ElInput: typeof import('element-ui/lib/input')['default']
    ElMain: typeof import('element-ui/lib/main')['default']
    ElMenu: typeof import('element-ui/lib/menu')['default']
    ElMenuItem: typeof import('element-ui/lib/menu-item')['default']
    ElMenuItemGroup: typeof import('element-ui/lib/menu-item-group')['default']
    ElMg: typeof import('element-ui/lib/mg')['default']
    ElOption: typeof import('element-ui/lib/option')['default']
    ElPagination: typeof import('element-ui/lib/pagination')['default']
    ElSelect: typeof import('element-ui/lib/select')['default']
    ElSubmenu: typeof import('element-ui/lib/submenu')['default']
    ElTable: typeof import('element-ui/lib/table')['default']
    ElTableColumn: typeof import('element-ui/lib/table-column')['default']
    ElTimePicker: typeof import('element-ui/lib/time-picker')['default']
    ElTooltip: typeof import('element-ui/lib/tooltip')['default']
    ElTree: typeof import('element-ui/lib/tree')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
